<?php include 'header.php';?>
<?php include 'menu.php';?>
    <main class="content">
        <div>
            <h1 style="text-align:center;">Newsletter Archive</h1>
            <table class="newsletter-archive">
                <tr>
                    <th>Year</th>
                    <th>Season</th>
                    <th></th>
                </tr>
                <tr>
                    <td>2021</td>
                    <td>Fall</td>
                    <td><a href="newsletters/HFH News Fall 2021.pdf">Download</a></td>
                </tr>
                <tr>
                    <td>2021</td>
                    <td>February</td>
                    <td><a href="newsletters/HFH News Feb 2021.pdf">Download</a></td>
                </tr>
                <tr>
                    <td>2020</td>
                    <td>August</td>
                    <td><a href="newsletters/2020 August.pdf">Download</a></td>
                </tr>
                <tr>
                    <td>2020</td>
                    <td>January</td>
                    <td>Download</td>
                </tr>
                <tr>
                    <td>2019</td>
                    <td>September</td>
                    <td>Download</td>
                </tr>
                <tr>
                    <td>2019</td>
                    <td>Summer</td>
                    <td>Download</td>
                </tr>
                <tr>
                    <td>2019</td>
                    <td>January</td>
                    <td>Download</td>
                </tr>
                <tr>
                    <td>2018</td>
                    <td>December</td>
                    <td>Download</td>
                </tr>
                <tr>
                    <td>2018</td>
                    <td>October</td>
                    <td>Download</td>
                </tr>
                <tr>
                    <td>2018</td>
                    <td>September</td>
                    <td>Download</td>
                </tr>
                <tr>
                    <td>2018</td>
                    <td>August</td>
                    <td>Download</td>
                </tr>
                <tr>
                    <td>2018</td>
                    <td>July</td>
                    <td>Download</td>
                </tr>
                <tr>
                    <td>2018</td>
                    <td>June</td>
                    <td>Download</td>
                </tr>
                <tr>
                    <td>2016</td>
                    <td>Fall</td>
                    <td>Download</td>
                </tr>
                <tr>
                    <td>2016</td>
                    <td>Spring</td>
                    <td>Download</td>
                </tr>
                <tr>
                    <td>2014</td>
                    <td>Fall</td>
                    <td>Download</td>
                </tr>
                <tr>
                    <td>2013</td>
                    <td>Summer</td>
                    <td>Download</td>
                </tr>
                <tr>
                    <td>2013</td>
                    <td>Spring</td>
                    <td>Download</td>
                </tr>
                <tr>
                    <td>2012</td>
                    <td>Summer</td>
                    <td>Download</td>
                </tr>
                <tr>
                    <td>2012</td>
                    <td>Spring</td>
                    <td>Download</td>
                </tr>
                <tr>
                    <td>2011</td>
                    <td>Summer</td>
                    <td>Download</td>
                </tr>
                <tr>
                    <td>2011</td>
                    <td>Spring</td>
                    <td>Download</td>
                </tr>
                <tr>
                    <td>2010</td>
                    <td>Fall</td>
                    <td>Download</td>
                </tr>
                <tr>
                    <td>2010</td>
                    <td>Summer</td>
                    <td>Download</td>
                </tr>
                <tr>
                    <td>2010</td>
                    <td>Spring</td>
                    <td>Download</td>
                </tr>
                <tr>
                    <td>2009</td>
                    <td>Fall</td>
                    <td>Download</td>
                </tr>
                <tr>
                    <td>2009</td>
                    <td>Summer</td>
                    <td>Download</td>
                </tr>
            </table>
        </div>
    </main>
<?php include 'footer.php';?>
<?php include 'closing.php';?>
